apiVersion: apps/v1
kind: Deployment
metadata:
  name: beautiful243
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beautiful243
  template:
    metadata:
      labels:
        app: beautiful243
    spec:
      containers:
      - image: okteto.dev/beautiful243:latest
        name: beautiful243
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "a404b9df-f976-4372-a972-f8a7286d99bb"
        - name: Vless_Path
          value: "/soekdhfye252"
        - name: Vmess_UUID
          value: "12d13593-6a72-4c9e-9851-2ab0f586bbe2"
        - name: Vmess_Path
          value: "/btudjfhuwe8"
        - name: Share_Path
          value: "/v2link"
