apiVersion: v1
kind: Service
metadata:
  name: beautiful243
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "beautiful243"
    port: 8080
  selector:
    app: beautiful243
